### ISSUE TITLE
Design for home page

### ISSUE THREAD

**Issue by prajjwalkapoor** [prajjwalkapoor/hall4-website#10]
Take ideas for content from https://www.iiitdmj.ac.in/hall3.iiitdmj.ac.in/ 
color theme need not be same

**Comment by Waishnav** [comment]
Aditya and I are done with the wireframe of the design so from now we can start the development process. And as we proceed we will update some parts of it and give the overall design.

**Comment by Waishnav** [comment]
Also, you can view the design here https://www.figma.com/file/ZvkpEgMiIBZ1XLpVdcP1s7/Hall-4-Webpage?node-id=168%3A4
