### ISSUE TITLE
[UI] Create Navbar

### ISSUE THREAD

**Issue by prajjwalkapoor** [prajjwalkapoor/hall4-website#13]
Create a responsive navbar according to the design https://www.figma.com/file/ZvkpEgMiIBZ1XLpVdcP1s7/Hall-4-Webpage?node-id=168%3A4 
Navbar is a global component so write CSS for the navbar only in the global CSS file. Also, use camel casing for writing class names.

**Comment by Waishnav** [comment]
Also, make sure to implement the following thing
The Navbar will be fixed at its position throughout the scroll, and on scrolling down a little bit (after passing down from the hero image), the background of the navbar will turn to white and the foreground text color will turn to black.

![image](https://user-images.githubusercontent.com/86405648/188304950-0bc36dd5-d734-4cae-98ed-0ba83343408d.png)

**Comment by Anurag607** [comment]
I am taking it
