### ISSUE TITLE
[UI] Create Footer for Home Page

### ISSUE THREAD

**Issue by Priyansh61** [prajjwalkapoor/hall4-website#19]
Create a responsive <b>Footer Section</b>  according to the given <a href="https://www.figma.com/file/ZvkpEgMiIBZ1XLpVdcP1s7/Hall-4-Webpage?node-id=168%3A4">design</a>.
<ul>
<li>Make sure to make change to the <a href="https://github.com/prajjwalkapoor/hall4-website/tree/master/ui/sections/footer/">folder</a>(directory) containing index.html and footer.css</li>

<li>Leave empty anchor tags for the required links for now.</li>
</ul>

<p><b>Image for reference :</b></p>
<img src="https://i.postimg.cc/sxvpQg8Z/footer.png" alt="about section">

**Comment by sdeepanshu17** [comment]
Can I work on this?

**Comment by developer-irfan** [comment]
@prajjwalkapoor i will create footer same as per design

**Comment by salted0dreams** [comment]
Can I be assigned for this?

**Comment by a1pharooster** [comment]
@sdeepanshu17  have you finished working on this?

**Comment by prajjwalkapoor** [comment]
> @prajjwalkapoor i will create footer same as per design

Hey @developer-irfan, thanks for showing interest in contributing to this project but we have started this project just for college mates to make them familiar with opensource and git.
If you want to contribute, you can check out [Kairy](https://github.com/prajjwalkapoor/kairy) and if you have anything to ask, you can contact me on [Twitter](https://twitter.com/the_prajjwal)
