### ISSUE TITLE
[UI] Create the facilites section 

### ISSUE THREAD

**Issue by Priyansh61** [prajjwalkapoor/hall4-website#20]
Create a <b>Facilities Section</b>  according to the <a type="_blank" href="https://www.figma.com/file/ZvkpEgMiIBZ1XLpVdcP1s7/Hall-4-Webpage?node-id=168%3A4">design</a>.
<ul>
<li>Make sure to make these change within this <a href="https://github.com/prajjwalkapoor/hall4-website/tree/master/ui/sections/facilities">folder</a> having index.html and about.css</li>
<li>Make sure to add proper description in the facilites section</li>
<li>You can also use a facilities.js file to create the button for see more.</li>
<li>Use icon of appropriate format and try to keep the size within 50kb</li>
<li> Try to add the responsiveness for mobile displays, for this you can just use flex wrap column</li>
</ul>

<b>Note: </b>Do your changes on a new branch, dont make commits to the master/main bramch.

<b>Image for Reference:</b>
<img src="https://i.postimg.cc/Y2d2hsXw/facilites.png">

**Comment by mittalvansh** [comment]
Can I be assigned to this?

**Comment by Priyansh61** [comment]
Definitely @mittalvansh Enjoy contributing..... :smile:
